# Generated by Django 3.2.18 on 2023-03-19 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='first_name',
            new_name='username',
        ),
    ]
