# Generated by Django 3.2.18 on 2023-03-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='special_occasion',
            field=models.TextField(default='No'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_requirements',
            field=models.TextField(default='None'),
        ),
    ]
